FROM amazon/aws-cli:latest

ARG TERRAFORM_VERSION
ARG TERRAGRUNT_VERSION

RUN apk add --update --no-cache bash git openssh

RUN cd /usr/local/bin && \
    wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip && \
    unzip terraform.zip terraform && \
    rm terraform.zip && \
    chmod +x terraform
 
RUN cd /usr/local/bin && \
    wget https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -O terragrunt && \
    chmod +x terragrunt

WORKDIR /apps

ENTRYPOINT []
